# Generated by Django 5.0.4 on 2026-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
