# Generated by Django 5.0.4 on 2026-05-13 11:28

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudropeuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path),
        ),
        migrations.AddField(
            model_name='cloudropeuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
